### ISSUE TITLE
Data contract

### ISSUE THREAD

**Issue by socramreysa** [Ceschrupp/Octopus#2]
Hablar con los pibes de Octupos y arreglar el data contract. 

Tenemos que saber que forma tienen los datos en cada enpoint que usamos.

**Comment by Ceschrupp** [comment]
- Login
- Datos del propietario
- Datos del consorcio

**Comment by Ceschrupp** [comment]
<p> holi </p>

**Comment by Ceschrupp** [comment]
<h1> holaaaa</h1>
